# # This file contains the fastlane.tools configuration
# # You can find the documentation at https://docs.fastlane.tools
# #
# # For a list of all available actions, check out
# #
# #     https://docs.fastlane.tools/actions
# #
# # For a list of all available plugins, check out
# #
# #     https://docs.fastlane.tools/plugins/available-plugins
# #

# # Uncomment the line if you want fastlane to automatically update itself
# # update_fastlane

# default_platform(:ios)

# platform :ios do
#   desc "Push a new beta build to TestFlight"
#   lane :beta do
#     increment_build_number(xcodeproj: "VideoDemo.xcodeproj")
#     build_app(workspace: "VideoDemo.xcworkspace", scheme: "VideoDemo")
#     upload_to_testflight
#   end
# end

default_platform(:ios)
 
platform :ios do
 desc "Push a new beta build to TestFlight"
 
 lane :internal do
     update_fastlane
 end
  lane :get_app_store_connect_api_key do
   app_store_connect_api_key(
     key_id: "66233FLTPJ", #Your Auth key ID
     issuer_id: "9389fe93-4b9b-4ba5-bff5-0470887755f9",#Your Auth key Issuer ID
     key_filepath: "fastlane/AuthKey_66233FLTPJ.p8",
     in_house: false,
   )
 end
 
 desc "Increment version prod"
 lane :increment_version_prod do
 
   final_version = get_version_number     
   final_build_number =  increment_build_number
 
   puts "Final Version " + final_version
   puts "Final Build Number " + final_build_number
   ENV["VERSION"] = final_version
   ENV["BUILD_NUMBER"] = final_build_number
 
 end
 
 #builds app
 lane :build_to_testflight do
 
   puts "Preparing TestFlight Build - Make sure you have updated the Build Version & Number Otherwise Testflight will reject it."
 
   sigh(api_key: get_app_store_connect_api_key , app_identifier: "org.reactjs.native.example.Foodienator") #Replace with Your package name
 
   ipa = gym(
     scheme: "VideoDemo", #Replace with Your scheme
     workspace: "VideoDemo.xcworkspace", #Replace with Your workspace
     export_method: "app-store",
     output_directory: "build"
   )
 
   puts "Pushing build to testflight"
 
   pilot(api_key: get_app_store_connect_api_key,
     ipa: ipa,
     app_identifier: "org.reactjs.native.example.Foodienator",
     skip_waiting_for_build_processing: true,
     skip_submission: true,
     distribute_external: false,
     notify_external_testers: false
   )
    puts "Testflight Build Succeed"
 
 end
 
 # slack(
 #      message: "New Testflight Vesrion for the App is available.",
 #      success: true,
 #      slack_url: "https://hooks.slack.com/services/IL8ULJ5ND/P01YR68T9K4/ufhtlRT87jQ8rPQ4XNuqrUps"
 #  ) #replace the url with your “Slack Webhook URL” so your slack group can be notified whenever fastlane releases a build to testflight.
 # end
 
 
 # lane :submit_review_ios do
 #   deliver(
 #     submit_for_review: true,
 #     automatic_release: true,
 #     force: true, # Skip HTMl report verification
 #     skip_metadata: true,
 #     skip_screenshots: true,
 #     skip_binary_upload: true
 #   )
 # end
end
